package com.bubaum.pairing_server.enums

enum class DeliveryCompany(val code: String, val company: String) {
    CJ("04", "CJ대한통운"),
    HANJIN("05", "한진택배"),
    LOTTE("08", "롯데택배"),
    POST("01", "우체국택배"),
    LOGEN("06", "로젠택배"),
    ILYANG("11", "일양로지스"),
    HANDEX("20", "한덱스"),
    DAESIN("22", "대신택배"),
    KYUNGDONG("23", "경동택배"),
    HAPDONG("32", "합동택배"),
    CU("46", "CU 편의점택배"),
    GSPOSTBOX("24", "GS Postbox 택배"),
    HANSARANG("16", "한의사랑택배"),
    CHUNIL("17", "천일택배"),
    GEONYOUNG("18", "건영택배"),
    GOODTRUCK("40", "굿투럭"),
    ANYTRAK("43", "애니트랙"),
    SLX("44", "SLX택배"),
    WOORI("45", "우리택배(구호남택배)"),
    WOORIHANBANG("47", "우리한방택배"),
    NHNONGHYUP("53", "농협택배"),
    HOMEPICK("54", "홈픽택배"),
    IKLOGISTICS("71", "IK물류"),
    SUNGHUN("72", "성훈물류"),
    YONGMA("74", "용마로지스"),
    WONDERQUICK("75", "원더스퀵"),
    LOGISVALLEY("79", "로지스밸리택배"),
    CULLINEXTMILE("82", "컬리넥스트마일"),
    FULLATHOME("85", "풀앳홈"),
    SAMSUNGLOGISTICS("86", "삼성전자물류"),
    QURUN("88", "큐런택배"),
    DOOBALHERO("89", "두발히어로"),
    WINIADIMCHAE("90", "위니아딤채"),
    GENIGO("92", "지니고 당일배송"),
    TODAYPICKUP("94", "오늘의픽업"),
    LOGISVALLEY2("96", "로지스밸리"),
    HANSAM("101", "한샘서비스원 택배"),
    NDEXKOREA("103", "NDEX KOREA"),
    DODOFLEX("104", "도도플렉스(dodoflex)"),
    LGPANTOS("107", "LG전자(판토스)"),
    BUREUNG("110", "부릉"),
    HOME1004("112", "1004홈"),
    THUNDERHERO("113", "썬더히어로"),
    TEAMFRESH("116", "(주)팀프레시"),
    LOTTECHILSUNG("118", "롯데칠성"),
    PINGPONG("119", "핑퐁"),
    VALEX("120", "발렉스 특수물류"),
    NTELPFS("123", "엔티엘피스"),
    GTSLOGIS("125", "GTS로지스"),
    LOGISPOT("127", "로지스팟"),
    HOMEPICKTODAY("129", "홈픽 오늘도착"),
    LOGISPARTNER("130", "로지스파트너"),
    DELIVERABIT("131", "딜리래빗"),
    GEOP("132", "지오피"),
    HKHOLDINGS("134", "에이치케이홀딩스"),
    HTNS("135", "HTNS"),
    KJT("136", "케이제이티"),
    THEBAO("137", "더바오"),
    LASTMILE("138", "라스트마일"),
    TODAYRUSH("139", "오늘회 러쉬"),
    TANGOANDGO("142", "탱고앤고"),
    TODAY("143", "투데이"),
    HYUNDAIGLOVIS("145", "현대글로비스"),
    ARGO("148", "ARGO"),
    GIANT("151", "자이언트"),
    HY("155", "HY"),
    YUPYLOGIS("156", "유피로지스"),
    WOOJIN("157", "우진인터로지스"),
    SAMDASU("159", "삼다수 가정배송"),
    WIDETECH("160", "와이드테크"),
    WINIONLOGIS("163", "위니온로지스"),
    DELIBOX("167", "딜리박스");


    companion object {
        fun getByCode(code: String): DeliveryCompany? {
            return values().find { it.code == code }
        }

    }
}